[package]
name = "gbc"
version = "0.1.0"
edition = "2021"

[dependencies]
byteorder = "1.5.0"
enumn = "0.1.13"
lazy_static = "1.4.0"
phf = { version = "0.11.2", features = ["macros"] }
serde_json = "1.0.116"
